var runes = [
    { label: "rune pa age", category: "pa", icon: "/images/runes/pa/rune_pa_age.png"},
    { label: "rune pa cha", category: "pa", icon: "/images/runes/pa/rune_pa_cha.png"},
    { label: "rune pa do air", category: "pa", icon: "/images/runes/pa/rune_pa_do_air.png"},
    { label: "rune pa do cri", category: "pa", icon: "/images/runes/pa/rune_pa_do_cri.png"},
    { label: "rune pa do eau", category: "pa", icon: "/images/runes/pa/rune_pa_do_eau.png"},
    { label: "rune pa do feu", category: "pa", icon: "/images/runes/pa/rune_pa_do_feu.png"},
    { label: "rune pa do neutre", category: "pa", icon: "/images/runes/pa/rune_pa_do_neutre.png"},
    { label: "rune pa do pou", category: "pa", icon: "/images/runes/pa/rune_pa_do_pou.png"},
    { label: "rune pa do terre", category: "pa", icon: "/images/runes/pa/rune_pa_do_terre.png"},
    { label: "rune pa fo", category: "pa", icon: "/images/runes/pa/rune_pa_fo.png"},
    { label: "rune pa fui", category: "pa", icon: "/images/runes/pa/rune_pa_fui.png"},
    { label: "rune pa ine", category: "pa", icon: "/images/runes/pa/rune_pa_ine.png"},
    { label: "rune pa ini", category: "pa", icon: "/images/runes/pa/rune_pa_ini.png"},
    { label: "rune pa pi", category: "pa", icon: "/images/runes/pa/rune_pa_pi.png"},
    { label: "rune pa pi per", category: "pa", icon: "/images/runes/pa/rune_pa_pi_per.png"},
    { label: "rune pa pod", category: "pa", icon: "/images/runes/pa/rune_pa_pod.png"},
    { label: "rune pa prospe", category: "pa", icon: "/images/runes/pa/rune_pa_prospe.png"},
    { label: "rune pa pui", category: "pa", icon: "/images/runes/pa/rune_pa_pui.png"},
    { label: "rune pa ret pa", category: "pa", icon: "/images/runes/pa/rune_pa_ret_pa.png"},
    { label: "rune pa ret pme", category: "pa", icon: "/images/runes/pa/rune_pa_ret_pme.png"},
    { label: "rune pa ré air", category: "pa", icon: "/images/runes/pa/rune_pa_ré_air.png"},
    { label: "rune pa ré cri", category: "pa", icon: "/images/runes/pa/rune_pa_ré_cri.png"},
    { label: "rune pa ré eau", category: "pa", icon: "/images/runes/pa/rune_pa_ré_eau.png"},
    { label: "rune pa ré feu", category: "pa", icon: "/images/runes/pa/rune_pa_ré_feu.png"},
    { label: "rune pa ré neutre", category: "pa", icon: "/images/runes/pa/rune_pa_ré_neutre.png"},
    { label: "rune pa ré pa", category: "pa", icon: "/images/runes/pa/rune_pa_ré_pa.png"},
    { label: "rune pa ré pme", category: "pa", icon: "/images/runes/pa/rune_pa_ré_pme.png"},
    { label: "rune pa ré pou", category: "pa", icon: "/images/runes/pa/rune_pa_ré_pou.png"},
    { label: "rune pa ré terre", category: "pa", icon: "/images/runes/pa/rune_pa_ré_terre.png"},
    { label: "rune pa sa", category: "pa", icon: "/images/runes/pa/rune_pa_sa.png"},
    { label: "rune pa so", category: "pa", icon: "/images/runes/pa/rune_pa_so.png"},
    { label: "rune pa tac", category: "pa", icon: "/images/runes/pa/rune_pa_tac.png"},
    { label: "rune pa vi", category: "pa", icon: "/images/runes/pa/rune_pa_vi.png"},
    { label: "rune ra age", category: "ra", icon: "/images/runes/ra/rune_ra_age.png"},
    { label: "rune ra cha", category: "ra", icon: "/images/runes/ra/rune_ra_cha.png"},
    { label: "rune ra fo", category: "ra", icon: "/images/runes/ra/rune_ra_fo.png"},
    { label: "rune ra ine", category: "ra", icon: "/images/runes/ra/rune_ra_ine.png"},
    { label: "rune ra ini", category: "ra", icon: "/images/runes/ra/rune_ra_ini.png"},
    { label: "rune ra pi per", category: "ra", icon: "/images/runes/ra/rune_ra_pi_per.png"},
    { label: "rune ra pod", category: "ra", icon: "/images/runes/ra/rune_ra_pod.png"},
    { label: "rune ra pui", category: "ra", icon: "/images/runes/ra/rune_ra_pui.png"},
    { label: "rune ra sa", category: "ra", icon: "/images/runes/ra/rune_ra_sa.png"},
    { label: "rune ra vi", category: "ra", icon: "/images/runes/ra/rune_ra_vi.png"},
    { label: "rune age", category: "simple", icon: "/images/runes/simple/rune_age.png"},
    { label: "rune cha", category: "simple", icon: "/images/runes/simple/rune_cha.png"},
    { label: "rune cri", category: "simple", icon: "/images/runes/simple/rune_cri.png"},
    { label: "rune de chasse", category: "simple", icon: "/images/runes/simple/rune_de_chasse.png"},
    { label: "rune do", category: "simple", icon: "/images/runes/simple/rune_do.png"},
    { label: "rune do air", category: "simple", icon: "/images/runes/simple/rune_do_air.png"},
    { label: "rune do cri", category: "simple", icon: "/images/runes/simple/rune_do_cri.png"},
    { label: "rune do eau", category: "simple", icon: "/images/runes/simple/rune_do_eau.png"},
    { label: "rune do feu", category: "simple", icon: "/images/runes/simple/rune_do_feu.png"},
    { label: "rune do neutre", category: "simple", icon: "/images/runes/simple/rune_do_neutre.png"},
    { label: "rune do per ar", category: "simple", icon: "/images/runes/simple/rune_do_per_ar.png"},
    { label: "rune do per di", category: "simple", icon: "/images/runes/simple/rune_do_per_di.png"},
    { label: "rune do per mé", category: "simple", icon: "/images/runes/simple/rune_do_per_mé.png"},
    { label: "rune do per so", category: "simple", icon: "/images/runes/simple/rune_do_per_so.png"},
    { label: "rune do pou", category: "simple", icon: "/images/runes/simple/rune_do_pou.png"},
    { label: "rune do ren", category: "simple", icon: "/images/runes/simple/rune_do_ren.png"},
    { label: "rune do terre", category: "simple", icon: "/images/runes/simple/rune_do_terre.png"},
    { label: "rune fo", category: "simple", icon: "/images/runes/simple/rune_fo.png"},
    { label: "rune fui", category: "simple", icon: "/images/runes/simple/rune_fui.png"},
    { label: "rune ga pa", category: "simple", icon: "/images/runes/simple/rune_ga_pa.png"},
    { label: "rune ga pme", category: "simple", icon: "/images/runes/simple/rune_ga_pme.png"},
    { label: "rune ine", category: "simple", icon: "/images/runes/simple/rune_ine.png"},
    { label: "rune ini", category: "simple", icon: "/images/runes/simple/rune_ini.png"},
    { label: "rune invo", category: "simple", icon: "/images/runes/simple/rune_invo.png"},
    { label: "rune pi", category: "simple", icon: "/images/runes/simple/rune_pi.png"},
    { label: "rune pi per", category: "simple", icon: "/images/runes/simple/rune_pi_per.png"},
    { label: "rune po", category: "simple", icon: "/images/runes/simple/rune_po.png"},
    { label: "rune pod", category: "simple", icon: "/images/runes/simple/rune_pod.png"},
    { label: "rune prospe", category: "simple", icon: "/images/runes/simple/rune_prospe.png"},
    { label: "rune pui", category: "simple", icon: "/images/runes/simple/rune_pui.png"},
    { label: "rune ret pa", category: "simple", icon: "/images/runes/simple/rune_ret_pa.png"},
    { label: "rune ret pme", category: "simple", icon: "/images/runes/simple/rune_ret_pme.png"},
    { label: "rune ré air", category: "simple", icon: "/images/runes/simple/rune_ré_air.png"},
    { label: "rune ré cri", category: "simple", icon: "/images/runes/simple/rune_ré_cri.png"},
    { label: "rune ré eau", category: "simple", icon: "/images/runes/simple/rune_ré_eau.png"},
    { label: "rune ré feu", category: "simple", icon: "/images/runes/simple/rune_ré_feu.png"},
    { label: "rune ré neutre", category: "simple", icon: "/images/runes/simple/rune_ré_neutre.png"},
    { label: "rune ré pa", category: "simple", icon: "/images/runes/simple/rune_ré_pa.png"},
    { label: "rune ré per air", category: "simple", icon: "/images/runes/simple/rune_ré_per_air.png"},
    { label: "rune ré per di", category: "simple", icon: "/images/runes/simple/rune_ré_per_di.png"},
    { label: "rune ré per eau", category: "simple", icon: "/images/runes/simple/rune_ré_per_eau.png"},
    { label: "rune ré per feu", category: "simple", icon: "/images/runes/simple/rune_ré_per_feu.png"},
    { label: "rune ré per mé", category: "simple", icon: "/images/runes/simple/rune_ré_per_mé.png"},
    { label: "rune ré per neutre", category: "simple", icon: "/images/runes/simple/rune_ré_per_neutre.png"},
    { label: "rune ré per terre", category: "simple", icon: "/images/runes/simple/rune_ré_per_terre.png"},
    { label: "rune ré pme", category: "simple", icon: "/images/runes/simple/rune_ré_pme.png"},
    { label: "rune ré pou", category: "simple", icon: "/images/runes/simple/rune_ré_pou.png"},
    { label: "rune ré terre", category: "simple", icon: "/images/runes/simple/rune_ré_terre.png"},
    { label: "rune sa", category: "simple", icon: "/images/runes/simple/rune_sa.png"},
    { label: "rune signature", category: "simple", icon: "/images/runes/simple/rune_signature.png"},
    { label: "rune so", category: "simple", icon: "/images/runes/simple/rune_so.png"},
    { label: "rune tac", category: "simple", icon: "/images/runes/simple/rune_tac.png"},
    { label: "rune vi", category: "simple", icon: "/images/runes/simple/rune_vi.png"},
];

$(document).ready(function() {
    // https://stackoverflow.com/questions/28285813/style-jquery-autocomplete-in-a-bootstrap-input-field
    $("#rune_searching").autocomplete({
        source : runes,
        minLength : 0
    });
});
