var runes = [
    "rune pa age",
    "rune pa cha",
    "rune pa do air",
    "rune pa do cri",
    "rune pa do eau",
    "rune pa do feu",
    "rune pa do neutre",
    "rune pa do pou",
    "rune pa do terre",
    "rune pa fo",
    "rune pa fui",
    "rune pa ine",
    "rune pa ini",
    "rune pa pi",
    "rune pa pi per",
    "rune pa pod",
    "rune pa prospe",
    "rune pa pui",
    "rune pa ret pa",
    "rune pa ret pme",
    "rune pa ré air",
    "rune pa ré cri",
    "rune pa ré eau",
    "rune pa ré feu",
    "rune pa ré neutre",
    "rune pa ré pa",
    "rune pa ré pme",
    "rune pa ré pou",
    "rune pa ré terre",
    "rune pa sa",
    "rune pa so",
    "rune pa tac",
    "rune pa vi",
    "rune ra age",
    "rune ra cha",
    "rune ra fo",
    "rune ra ine",
    "rune ra ini",
    "rune ra pi per",
    "rune ra pod",
    "rune ra pui",
    "rune ra sa",
    "rune ra vi",
    "rune age",
    "rune cha",
    "rune cri",
    "rune de chasse",
    "rune do",
    "rune do air",
    "rune do cri",
    "rune do eau",
    "rune do feu",
    "rune do neutre",
    "rune do per ar",
    "rune do per di",
    "rune do per mé",
    "rune do per so",
    "rune do pou",
    "rune do ren",
    "rune do terre",
    "rune fo",
    "rune fui",
    "rune ga pa",
    "rune ga pme",
    "rune ine",
    "rune ini",
    "rune invo",
    "rune pi",
    "rune pi per",
    "rune po",
    "rune pod",
    "rune prospe",
    "rune pui",
    "rune ret pa",
    "rune ret pme",
    "rune ré air",
    "rune ré cri",
    "rune ré eau",
    "rune ré feu",
    "rune ré neutre",
    "rune ré pa",
    "rune ré per air",
    "rune ré per di",
    "rune ré per eau",
    "rune ré per feu",
    "rune ré per mé",
    "rune ré per neutre",
    "rune ré per terre",
    "rune ré pme",
    "rune ré pou",
    "rune ré terre",
    "rune sa",
    "rune signature",
    "rune so",
    "rune tac",
    "rune vi"
];

$(document).ready(function() {
    // https://stackoverflow.com/questions/28285813/style-jquery-autocomplete-in-a-bootstrap-input-field
    $("#rune_searching").autocomplete({
        source : runes,
        minLength : 0
    });
});
